use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::geometry::MemoryCoordinates;
use crate::medium::Modality;
use crate::wave::WaveParams;

/// An explicit skip link between two memories.
///
/// ⚠ The name and the old doc comment lie about this type, and the lie is
/// dangerous: it said "Stub type … Inert", which reads as an invitation to
/// delete it. It is not inert. Dream consolidation WRITES these — `link_span`
/// and the bridge-forming stages in `consolidation.rs` push a forward and a
/// reverse `LegacyLink` for every pair they decide to associate — and several
/// live readers depend on them:
///
/// - `consolidation.rs` bridge-node detection: a memory is a bridge when its
///   links reach 3+ clusters.
/// - `bridge.rs` counts skip-link edges to compute cluster degree.
/// - `research.rs` reports how many bridges are linked at all.
/// - `kannaka.rs` / `handlers/ops.rs` expose them, and rank "most connected"
///   memories by `connections.len()`.
///
/// What IS true is that associations are ALSO emergent from interference in
/// the holographic medium; explicit skip links are a second, coarser structure
/// laid on top, not a superseded one. The `Legacy` in the name is historical
/// and renaming it is a serialization-visible change, so the name stays and
/// this comment carries the correction. See #792.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LegacyLink {
    pub target_id: Uuid,
    pub strength: f32,
    #[serde(default)]
    pub resonance_key: Vec<f32>,
    #[serde(default)]
    pub span: u8,
}

// ---------------------------------------------------------------------------
// Collective memory types (ADR-0011)
// ---------------------------------------------------------------------------

/// Record of a single merge operation applied to this memory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MergeRecord {
    pub merged_at: DateTime<Utc>,
    /// Agent whose memory was merged in
    pub source_agent: String,
    pub source_memory_id: String,
    /// "constructive" | "destructive" | "partial"
    pub merge_type: String,
    pub phase_diff: f32,
    pub amplitude_before: f32,
    pub amplitude_after: f32,
    /// The source memory's `sync_version` at the moment it was merged in. The
    /// idempotency guard rejects a re-broadcast whose `sync_version` is <= the
    /// highest already merged from that (agent, memory) — comparing against the
    /// SOURCE's own counter, not the local one (which every unrelated merge
    /// bumps and is therefore not comparable across agents). `#[serde(default)]`
    /// keeps pre-existing persisted records (which read back as 0) loadable.
    #[serde(default)]
    pub source_sync_version: u64,
}

fn default_agent() -> String {
    "local".to_string()
}

/// A memory that exists has been seen at least once. See
/// [`HyperMemory::times_seen`] for why the default is 1 and not 0.
fn default_times_seen() -> u32 {
    1
}

// ---------------------------------------------------------------------------
// HyperMemory
// ---------------------------------------------------------------------------

/// A hypervector memory with wave-modulated dynamics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HyperMemory {
    pub id: Uuid,
    /// Hypervector representation (d=10,000)
    pub vector: Vec<f32>,
    /// Wave amplitude
    pub amplitude: f32,
    /// Wave frequency
    pub frequency: f32,
    /// Wave phase
    pub phase: f32,
    /// Exponential decay rate (per-day; λ=0.001 → half-life ~693 days)
    pub decay_rate: f32,
    /// Creation timestamp
    pub created_at: DateTime<Utc>,
    /// Temporal layer (0=immediate, 1=day, 2=week, etc.)
    pub layer_depth: u8,
    /// Explicit skip links to other memories. **Actively written and read** —
    /// see [`LegacyLink`] for the full list of producers and consumers. The
    /// previous comment here described it as a backward-compatibility stub
    /// awaiting removal, which was wrong on both counts: dream consolidation
    /// populates it every cycle, and bridge-node detection would silently stop
    /// finding bridges if it went away. #792.
    ///
    /// Persisted, but NOT in the HRM binary and not via `WavefrontMeta` —
    /// `hrm_store` writes a separate **link-graph sidecar** and restores from
    /// it on load, and `rebuild_cache` snapshots and re-attaches these across
    /// the cache clear. Which is itself the evidence that they are load-bearing:
    /// `origin_agent`, genuinely rebuilt state, got no such treatment and comes
    /// back as `"local"` every restart (ADR-0056). This field was given a
    /// sidecar because losing it loses real structure.
    #[serde(default)]
    pub connections: Vec<LegacyLink>,
    /// Original text content (for debugging/migration)
    pub content: String,
    /// Whether this memory was generated by hallucination during dreaming
    #[serde(default)]
    pub hallucinated: bool,
    /// Parent memory IDs for hallucinated memories (lineage tracking)
    #[serde(default)]
    pub parents: Vec<String>,
    /// Geometric coordinates in SGA space
    #[serde(default)]
    pub geometry: Option<MemoryCoordinates>,
    /// Ξ (Xi) signature for consciousness differentiation - the non-commutative residue
    #[serde(default)]
    pub xi_signature: Vec<f32>,
    // --- ADR-0011: Collective memory fields ---
    /// Which agent created this memory ("local" for single-agent use)
    #[serde(default = "default_agent")]
    pub origin_agent: String,
    /// Monotonic version counter for sync conflict detection
    #[serde(default)]
    pub sync_version: u64,
    /// History of merge operations applied to this memory
    #[serde(default)]
    pub merge_history: Vec<MergeRecord>,
    /// When was this memory last processed by a dream consolidation cycle
    #[serde(default)]
    pub last_consolidated_at: Option<DateTime<Utc>>,
    /// Whether this memory has unresolved destructive interference with another agent's memory
    #[serde(default)]
    pub disputed: bool,
    /// Last time any field was mutated (amplitude, phase, vector, metadata).
    /// Used by incremental dreaming to identify changed memories.
    #[serde(default)]
    pub updated_at: Option<DateTime<Utc>>,
    /// Number of times this memory has been retrieved/recalled.
    /// Each retrieval adds energy to the wave function (EXP-003: f(x) term).
    #[serde(default)]
    pub retrieval_count: u32,
    /// How many times the world has SHOWN this fact — one per `remember` of
    /// the identical text, not per recall. `retrieval_count` above counts the
    /// times *we* went looking; this counts the times the fact came to us,
    /// which is the salience signal a repeated observation actually carries.
    ///
    /// A memory stored once and never repeated reads `1`, not `0` — the
    /// default exists so records serialized before this field came back as a
    /// truthful count rather than claiming the fact was never seen.
    ///
    /// Persisted by `HrmStore` in the `.times_seen.json` sidecar, for the same
    /// reason `retrieval_count` uses `.reactivation.json`: appending to the
    /// bincode `WavefrontMeta` layout means extending a positional format and
    /// its fallback-struct chain, and a sidecar carries zero format risk.
    #[serde(default = "default_times_seen")]
    pub times_seen: u32,
    /// Sensory modality of this memory (NCS Phase 1.1)
    #[serde(default)]
    pub modality: Modality,
    /// Retention tier (ADR-0031). Mirror of the canonical WavefrontMeta.tier,
    /// populated when the cache is built so triage can filter by tier without
    /// reaching into the medium. Not the persistence source of truth.
    #[serde(default)]
    pub tier: crate::medium::types::Tier,
    /// Wave 3 Task 3.2b — temporal-truth bounds, mirrored from the canonical
    /// `WavefrontMeta` when the cache is built (same pattern as `tier`). Not the
    /// persistence source of truth. Consumed by [`crate::temporal::TemporalSpec`]
    /// to discount Expired/Future facts in sensemaking.
    /// When the fact became true (None = always / unknown).
    #[serde(default)]
    pub effective_at: Option<DateTime<Utc>>,
    /// When this agent observed the fact (None = fall back to `created_at`).
    #[serde(default)]
    pub observed_at: Option<DateTime<Utc>>,
    /// When the fact stops being true (None = no known expiry).
    #[serde(default)]
    pub expires_at: Option<DateTime<Utc>>,
}

impl HyperMemory {
    /// Create a new memory with default wave parameters.
    pub fn new(vector: Vec<f32>, content: String) -> Self {
        let wave = WaveParams::default();
        Self {
            id: Uuid::new_v4(),
            vector,
            amplitude: wave.amplitude,
            frequency: wave.frequency,
            phase: wave.phase,
            decay_rate: wave.decay_rate,
            created_at: Utc::now(),
            layer_depth: 0,
            connections: Vec::new(),
            content,
            hallucinated: false,
            parents: Vec::new(),
            geometry: None,
            xi_signature: Vec::new(),
            origin_agent: default_agent(),
            sync_version: 0,
            merge_history: Vec::new(),
            last_consolidated_at: None,
            disputed: false,
            updated_at: None,
            retrieval_count: 0,
            times_seen: default_times_seen(),
            modality: Modality::default(),
            tier: crate::medium::types::Tier::default(),
            effective_at: None,
            observed_at: None,
            expires_at: None,
        }
    }

    /// Mark this memory as modified (stamps `updated_at`).
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    fn wave_params(&self) -> WaveParams {
        WaveParams {
            amplitude: self.amplitude,
            frequency: self.frequency,
            phase: self.phase,
            decay_rate: self.decay_rate,
        }
    }

    /// Compute effective strength at a given time:
    /// S(t) = (A + retrieval_energy) · cos(2πft+φ) · e^(-λt)
    pub fn effective_strength(&self, now: DateTime<Utc>) -> f32 {
        let age = (now - self.created_at).num_milliseconds().max(0) as f64 / 1000.0;
        crate::wave::compute_strength_with_retrieval(&self.wave_params(), age, self.retrieval_count)
    }

    /// Record a retrieval event — called on search/recall to boost the f(x) term.
    pub fn record_retrieval(&mut self) {
        self.retrieval_count = self.retrieval_count.saturating_add(1);
        // Do NOT renew the recovery window for a soft-deleted (ghost) memory.
        // `touch()` stamps `updated_at = now`, which stage_compact_ghosts reads
        // as "last meaningful activity" to decide when a ghost may be reclaimed.
        // If an incidental recall match kept bumping it, a ghost that still
        // happens to resonate with queries would never age out — defeating the
        // soft-delete. A live memory still touches.
        if self.amplitude != 0.0 {
            self.touch();
        }
    }

    /// Compute the effective vector: S(t) · h
    pub fn effective_vector(&self, now: DateTime<Utc>) -> Vec<f32> {
        let s = self.effective_strength(now);
        self.vector.iter().map(|&x| x * s).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Duration;

    #[test]
    fn effective_strength_diminishes() {
        let mut mem = HyperMemory::new(vec![1.0; 100], "test".into());
        mem.frequency = 0.0; // pure decay
        mem.decay_rate = 0.01;
        let t0 = mem.created_at;
        let s0 = mem.effective_strength(t0);
        let s1 = mem.effective_strength(t0 + Duration::seconds(100));
        let s2 = mem.effective_strength(t0 + Duration::seconds(1000));
        assert!(s0 > s1);
        assert!(s1 > s2);
    }

    #[test]
    fn effective_vector_scales_correctly() {
        let mut mem = HyperMemory::new(vec![0.5; 10], "test".into());
        mem.frequency = 0.0;
        mem.decay_rate = 0.001;
        let t0 = mem.created_at;
        let ev = mem.effective_vector(t0);
        // At t=0, S(0) = A·cos(φ)·e^0 = 1.0·1.0·1.0 = 1.0
        for &x in &ev {
            assert!((x - 0.5).abs() < 1e-5, "expected 0.5, got {x}");
        }

        let later = t0 + Duration::seconds(500);
        let ev2 = mem.effective_vector(later);
        let s = mem.effective_strength(later);
        for (i, &x) in ev2.iter().enumerate() {
            assert!((x - 0.5 * s).abs() < 1e-4, "mismatch at index {i}");
        }
    }

    #[test]
    fn hyper_memory_default_modality_is_unknown() {
        let mem = HyperMemory::new(vec![1.0; 10], "test".into());
        assert_eq!(mem.modality, Modality::Unknown);
    }

    #[test]
    fn hyper_memory_modality_deserializes_from_json_without_field() {
        // Backward compat: old serialized data missing the modality field
        let json = serde_json::json!({
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "vector": [0.1, 0.2, 0.3],
            "amplitude": 1.0,
            "frequency": 1.0,
            "phase": 0.0,
            "decay_rate": 0.001,
            "created_at": "2025-01-01T00:00:00Z",
            "layer_depth": 0,
            "content": "legacy memory"
        });
        let mem: HyperMemory = serde_json::from_value(json).unwrap();
        assert_eq!(mem.modality, Modality::Unknown);
        assert_eq!(mem.content, "legacy memory");
    }

    #[test]
    fn hyper_memory_modality_round_trips_through_json() {
        let mut mem = HyperMemory::new(vec![0.5; 10], "audio mem".into());
        mem.modality = Modality::Audio;
        let json = serde_json::to_string(&mem).unwrap();
        let deserialized: HyperMemory = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.modality, Modality::Audio);
    }
}
